"""Add frequency to service_types and act_items

Revision ID: 0655bc826d40
Revises: d0c1336ca8f8
Create Date: 2026-09-27 21:43:20.667592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0655bc826d40'
down_revision: Union[str, None] = 'd0c1336ca8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###