"""Add units table and link to service_types

Revision ID: 09ffae32a846
Revises: a725bc71b492
Create Date: 2026-09-26 09:56:41.835821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ffae32a846'
down_revision: Union[str, None] = 'a725bc71b492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('code', name=op.f('uq_units_code'))
    )
    op.add_column('service_types', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_service_types_unit_id_units'), 'service_types', 'units', ['unit_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('service_types', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_types', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_service_types_unit_id_units'), 'service_types', type_='foreignkey')
    op.drop_column('service_types', 'unit_id')
    op.drop_table('units')
    # ### end Alembic commands ###