"""fix users table __tablename__

Revision ID: 1480a1a30832
Revises: 9b30ef40ea38
Create Date: 2026-10-01 22:16:38.909994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1480a1a30832'
down_revision: Union[str, None] = '9b30ef40ea38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###