"""Change plan year to start_year and start_month

Revision ID: 24239f4ee8f1
Revises: 09ffae32a846
Create Date: 2026-09-26 10:59:43.862009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24239f4ee8f1'
down_revision: Union[str, None] = '09ffae32a846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_headers', sa.Column('start_year', sa.Integer(), nullable=False))
    op.add_column('plan_headers', sa.Column('start_month', sa.Integer(), nullable=False))
    op.drop_index('ix_plan_headers_object_year', table_name='plan_headers')
    op.drop_constraint('uq_plan_header', 'plan_headers', type_='unique')
    op.create_unique_constraint('uq_plan_header', 'plan_headers', ['object_id', 'start_year', 'start_month', 'name'])
    op.create_index('ix_plan_headers_object_period', 'plan_headers', ['object_id', 'start_year', 'start_month'], unique=False)
    op.drop_column('plan_headers', 'year')
    op.drop_constraint('uq_units_code', 'units', type_='unique')
    op.create_index(op.f('ix_units_code'), 'units', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_code'), table_name='units')
    op.create_unique_constraint('uq_units_code', 'units', ['code'])
    op.add_column('plan_headers', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('ix_plan_headers_object_period', table_name='plan_headers')
    op.drop_constraint('uq_plan_header', 'plan_headers', type_='unique')
    op.create_unique_constraint('uq_plan_header', 'plan_headers', ['object_id', 'year', 'name'])
    op.create_index('ix_plan_headers_object_year', 'plan_headers', ['object_id', 'year'], unique=False)
    op.drop_column('plan_headers', 'start_month')
    op.drop_column('plan_headers', 'start_year')
    # ### end Alembic commands ###