"""Add service categories and period_months

Revision ID: 53dae546a227
Revises: 951a661c6244
Create Date: 2026-09-26 21:50:16.852086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dae546a227'
down_revision: Union[str, None] = '951a661c6244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_service_categories_code'))
    )
    op.add_column('plan_headers', sa.Column('period_months', sa.Integer(), server_default='12', nullable=False))
    op.drop_constraint('uq_plan_header', 'plan_headers', type_='unique')
    op.create_unique_constraint('uq_plan_header', 'plan_headers', ['object_id', 'start_year', 'start_month', 'period_months', 'name'])
    op.add_column('service_types', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_service_types_category_id_service_categories'), 'service_types', 'service_categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('service_types', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_types', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_service_types_category_id_service_categories'), 'service_types', type_='foreignkey')
    op.drop_column('service_types', 'category_id')
    op.drop_constraint('uq_plan_header', 'plan_headers', type_='unique')
    op.create_unique_constraint('uq_plan_header', 'plan_headers', ['object_id', 'start_year', 'start_month', 'name'])
    op.drop_column('plan_headers', 'period_months')
    op.drop_table('service_categories')
    # ### end Alembic commands ###