"""add audit_logs table

Revision ID: 5eb0d374c043
Revises: 54e7d9928396
Create Date: 2026-10-03 22:17:22.853044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb0d374c043'
down_revision: Union[str, None] = '54e7d9928396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objects', 'area_sqm',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
    op.create_index('ix_objects_type_active', 'objects', ['type', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_objects_type_active', table_name='objects')
    op.alter_column('objects', 'area_sqm',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###