"""Change plan year to start_year and start_month

Revision ID: 67afdfae519a
Revises: 24239f4ee8f1
Create Date: 2026-09-26 11:15:41.347447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67afdfae519a'
down_revision: Union[str, None] = '24239f4ee8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###