"""add unit_price to plan_monthly

Revision ID: 68f36ea567e0
Revises: 88ad48eecb9b
Create Date: 2026-09-28 22:49:03.876071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f36ea567e0'
down_revision: Union[str, None] = '88ad48eecb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###