"""Add object_id to service_rates

Revision ID: 88ad48eecb9b
Revises: 9572ed1ef604
Create Date: 2026-09-28 22:08:02.569907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ad48eecb9b'
down_revision: Union[str, None] = '9572ed1ef604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_rates', sa.Column('object_id', sa.Integer(), nullable=True))
    op.drop_index('ix_service_rates_valid', table_name='service_rates')
    op.create_index('ix_service_rates_valid', 'service_rates', ['object_id', 'service_type_id', 'valid_from'], unique=False)
    op.drop_constraint('uq_service_rate_period', 'service_rates', type_='unique')
    op.create_unique_constraint('uq_service_rate_period', 'service_rates', ['object_id', 'service_type_id', 'valid_from'])
    op.create_foreign_key(op.f('fk_service_rates_object_id_objects'), 'service_rates', 'objects', ['object_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_service_rates_object_id_objects'), 'service_rates', type_='foreignkey')
    op.drop_constraint('uq_service_rate_period', 'service_rates', type_='unique')
    op.create_unique_constraint('uq_service_rate_period', 'service_rates', ['service_type_id', 'valid_from'])
    op.drop_index('ix_service_rates_valid', table_name='service_rates')
    op.create_index('ix_service_rates_valid', 'service_rates', ['service_type_id', 'valid_from'], unique=False)
    op.drop_column('service_rates', 'object_id')
    # ### end Alembic commands ###