"""Add tariff_base as string to objects

Revision ID: 951a661c6244
Revises: 67afdfae519a
Create Date: 2026-09-26 21:02:20.101454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '951a661c6244'
down_revision: Union[str, None] = '67afdfae519a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('tariff_base', sa.String(length=20), server_default='area', nullable=False))
    op.alter_column('objects', 'type',
               existing_type=postgresql.ENUM('MKD', 'PARKING', name='objecttype'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objects', 'type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('MKD', 'PARKING', name='objecttype'),
               existing_nullable=False)
    op.drop_column('objects', 'tariff_base')
    # ### end Alembic commands ###