"""fix users table __tablename__

Revision ID: 9b30ef40ea38
Revises: 2f86720e82fc
Create Date: 2026-10-01 00:00:11.908178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b30ef40ea38'
down_revision: Union[str, None] = '2f86720e82fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###