"""Add plan_monthly table

Revision ID: a725bc71b492
Revises: f9542ba101f3
Create Date: 2026-09-26 09:06:27.003041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a725bc71b492'
down_revision: Union[str, None] = 'f9542ba101f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_monthly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_item_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], name=op.f('fk_plan_monthly_plan_item_id_plan_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_monthly')),
    sa.UniqueConstraint('plan_item_id', 'month', 'year', name='uq_plan_monthly_item_month')
    )
    op.create_index('ix_plan_monthly_item', 'plan_monthly', ['plan_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plan_monthly_item', table_name='plan_monthly')
    op.drop_table('plan_monthly')
    # ### end Alembic commands ###