"""Add pricing settings table

Revision ID: a9084baa7af1
Revises: da560a16387e
Create Date: 2026-09-29 22:28:15.790585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9084baa7af1'
down_revision: Union[str, None] = 'da560a16387e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_pricing_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True, comment='NULL = для всех объектов'),
    sa.Column('service_type_id', sa.Integer(), nullable=True, comment='NULL = для всех услуг'),
    sa.Column('overhead_percent', sa.Numeric(precision=5, scale=2), nullable=False, comment='Накладные расходы %'),
    sa.Column('profit_percent', sa.Numeric(precision=5, scale=2), nullable=False, comment='Норма прибыли %'),
    sa.Column('vat_percent', sa.Numeric(precision=5, scale=2), nullable=False, comment='НДС %'),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True, comment='NULL = бессрочно'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name=op.f('fk_service_pricing_settings_object_id_objects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], name=op.f('fk_service_pricing_settings_service_type_id_service_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_pricing_settings')),
    sa.UniqueConstraint('object_id', 'service_type_id', 'valid_from', name='uq_pricing_settings_period')
    )
    op.create_index('ix_pricing_settings_valid', 'service_pricing_settings', ['object_id', 'service_type_id', 'valid_from'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricing_settings_valid', table_name='service_pricing_settings')
    op.drop_table('service_pricing_settings')
    # ### end Alembic commands ###