"""Add frequency to service_types and act_items

Revision ID: d0c1336ca8f8
Revises: c4400cb39ee2
Create Date: 2026-09-27 21:22:30.563069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c1336ca8f8'
down_revision: Union[str, None] = 'c4400cb39ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('act_items', sa.Column('frequency', sa.String(length=100), nullable=True))
    op.add_column('service_types', sa.Column('frequency', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_types', 'frequency')
    op.drop_column('act_items', 'frequency')
    # ### end Alembic commands ###