"""Add resources tables

Revision ID: da560a16387e
Revises: f94124a1a6ac
Create Date: 2026-09-29 22:18:34.414746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da560a16387e'
down_revision: Union[str, None] = 'f94124a1a6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plan_headers_object_period', table_name='plan_headers')
    op.drop_constraint('uq_plan_header', 'plan_headers', type_='unique')
    op.drop_column('plan_headers', 'updated_at')
    op.drop_column('plan_headers', 'approved_at')
    op.drop_column('plan_headers', 'approved_by')
    op.alter_column('plan_items', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('plan_items', 'frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('plan_items', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_plan_monthly_item', table_name='plan_monthly')
    op.drop_constraint('uq_plan_monthly_item_month', 'plan_monthly', type_='unique')
    op.create_unique_constraint('uq_plan_monthly_period', 'plan_monthly', ['plan_item_id', 'month', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_plan_monthly_period', 'plan_monthly', type_='unique')
    op.create_unique_constraint('uq_plan_monthly_item_month', 'plan_monthly', ['plan_item_id', 'month', 'year'])
    op.create_index('ix_plan_monthly_item', 'plan_monthly', ['plan_item_id'], unique=False)
    op.alter_column('plan_items', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    op.alter_column('plan_items', 'frequency',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('plan_items', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.add_column('plan_headers', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plan_headers', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('plan_headers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_plan_header', 'plan_headers', ['object_id', 'start_year', 'start_month', 'period_months', 'name'])
    op.create_index('ix_plan_headers_object_period', 'plan_headers', ['object_id', 'start_year', 'start_month'], unique=False)
    # ### end Alembic commands ###