"""Initial schema

Revision ID: f9542ba101f3
Revises: 
Create Date: 2026-09-25 20:22:06.707163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9542ba101f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('MKD', 'PARKING', name='objecttype'), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('spaces_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objects'))
    )
    op.create_index('ix_objects_type_active', 'objects', ['type', 'is_active'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('code', name=op.f('uq_resources_code'))
    )
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_types')),
    sa.UniqueConstraint('code', name=op.f('uq_service_types_code'))
    )
    op.create_table('fact_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='factstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name=op.f('fk_fact_headers_object_id_objects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_headers')),
    sa.UniqueConstraint('object_id', 'year', 'month', name='uq_fact_header_period')
    )
    op.create_index('ix_fact_headers_period', 'fact_headers', ['object_id', 'year', 'month'], unique=False)
    op.create_table('plan_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ARCHIVED', name='planstatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name=op.f('fk_plan_headers_object_id_objects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_headers')),
    sa.UniqueConstraint('object_id', 'year', 'name', name='uq_plan_header')
    )
    op.create_index('ix_plan_headers_object_year', 'plan_headers', ['object_id', 'year'], unique=False)
    op.create_table('resource_norms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_norms_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], name=op.f('fk_resource_norms_service_type_id_service_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_norms')),
    sa.UniqueConstraint('service_type_id', 'resource_id', 'valid_from', name='uq_resource_norm_period')
    )
    op.create_table('resource_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_rates_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_rates')),
    sa.UniqueConstraint('resource_id', 'valid_from', name='uq_resource_rate_period')
    )
    op.create_table('service_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], name=op.f('fk_service_rates_service_type_id_service_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_rates')),
    sa.UniqueConstraint('service_type_id', 'valid_from', name='uq_service_rate_period')
    )
    op.create_index('ix_service_rates_valid', 'service_rates', ['service_type_id', 'valid_from'], unique=False)
    op.create_table('acts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=False),
    sa.Column('act_date', sa.Date(), nullable=False),
    sa.Column('fact_header_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fact_header_id'], ['fact_headers.id'], name=op.f('fk_acts_fact_header_id_fact_headers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acts')),
    sa.UniqueConstraint('act_number', name=op.f('uq_acts_act_number'))
    )
    op.create_table('plan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_header_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['plan_header_id'], ['plan_headers.id'], name=op.f('fk_plan_items_plan_header_id_plan_headers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], name=op.f('fk_plan_items_service_type_id_service_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_items'))
    )
    op.create_table('act_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], name=op.f('fk_act_items_act_id_acts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], name=op.f('fk_act_items_service_type_id_service_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_act_items'))
    )
    op.create_table('fact_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fact_header_id', sa.Integer(), nullable=False),
    sa.Column('plan_item_id', sa.Integer(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('executed_at', sa.Date(), nullable=True),
    sa.Column('executor', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['fact_header_id'], ['fact_headers.id'], name=op.f('fk_fact_items_fact_header_id_fact_headers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], name=op.f('fk_fact_items_plan_item_id_plan_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], name=op.f('fk_fact_items_service_type_id_service_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_items'))
    )
    op.create_table('plan_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_item_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], name=op.f('fk_plan_resources_plan_item_id_plan_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_plan_resources_resource_id_resources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_resources'))
    )
    op.create_table('fact_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fact_item_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['fact_item_id'], ['fact_items.id'], name=op.f('fk_fact_resources_fact_item_id_fact_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_fact_resources_resource_id_resources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_resources'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_resources')
    op.drop_table('plan_resources')
    op.drop_table('fact_items')
    op.drop_table('act_items')
    op.drop_table('plan_items')
    op.drop_table('acts')
    op.drop_index('ix_service_rates_valid', table_name='service_rates')
    op.drop_table('service_rates')
    op.drop_table('resource_rates')
    op.drop_table('resource_norms')
    op.drop_index('ix_plan_headers_object_year', table_name='plan_headers')
    op.drop_table('plan_headers')
    op.drop_index('ix_fact_headers_period', table_name='fact_headers')
    op.drop_table('fact_headers')
    op.drop_table('service_types')
    op.drop_table('resources')
    op.drop_index('ix_objects_type_active', table_name='objects')
    op.drop_table('objects')
    # ### end Alembic commands ###